version: "3.8"

services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY:-your-username/resume-editor}/backend:${IMAGE_TAG:-latest}
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - ./backend/temp:/app/temp

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY:-your-username/resume-editor}/frontend:${IMAGE_TAG:-latest}
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=${FRONTEND_URL}
      - NEXT_PUBLIC_API_URL=${API_URL}
      - AUTH_SECRET=${AUTH_SECRET:-656b789ee183a77e8b01bab3666c14ce}
    depends_on:
      - backend
