version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/temp:/app/temp

  frontend:
    build:
      context: ./resume-editor
      args:
        NEXT_PUBLIC_API_URL: http://54.82.161.75:8000
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=http://54.82.161.75:3000
      - NEXT_PUBLIC_API_URL=http://54.82.161.75:8000
      - AUTH_SECRET=656b789ee183a77e8b01bab3666c14ce
    depends_on:
      - backend
