version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/temp:/app/temp

  frontend:
    build: ./resume-editor
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=http://localhost:3000
      - API_URL=http://backend:8000
    depends_on:
      - backend
