name: Deploy Resume Editor

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/oktagonia/resumeflow/backend:latest
          
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./resume-editor
          push: true
          tags: ghcr.io/oktagonia/resumeflow/frontend:latest
          build-args: |
            NEXTAUTH_URL=https://resume-flow.xyz
            NEXT_PUBLIC_API_URL=https://resume-flow.xyz/api
            AUTH_SECRET=${{ secrets.AUTH_SECRET }}
            AUTH_GITHUB_ID=${{ secrets.AUTH_GITHUB_ID }}
            AUTH_GITHUB_SECRET=${{ secrets.AUTH_GITHUB_SECRET }}
      
      - name: Deploy to EC2
        env:
          NEXT_PUBLIC_API_URL: https://resume-flow.xyz/api
        run: |
          # Create SSH key file
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          # Copy deployment script to EC2
          scp -i private_key.pem -o StrictHostKeyChecking=no deploy.sh ec2-user@${{ secrets.EC2_HOST }}:~/deploy.sh

          # SSH into EC2 and deploy
          ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "
            set -e
            chmod +x ~/deploy.sh
            export GITHUB_TOKEN='${{ secrets.GITHUB_TOKEN }}'
            export GITHUB_ACTOR='${{ github.actor }}'
            export GITHUB_REPOSITORY='oktagonia/resumeflow'
            export FRONTEND_URL='https://resume-flow.xyz'
            export NEXT_PUBLIC_API_URL='https://resume-flow.xyz/api'
            ~/deploy.sh
          "

          # Clean up SSH key
          rm private_key.pem
